### ISSUE TITLE
Add support for linking steps with custom parameter types

### ISSUE THREAD

**Issue by travispavek** [jlagerweij/cucumber-kotlin#11]
For a while now Cucumber-JVM as supported custom parameter types in the Cucumber expression. At the time these were a bit limited in functionality and defining them were a pain.  In Cucumber-JVM v5.0 the limitations have gone away and you can now define these parameters using a simple annotation. For this reason I think they will become fairly popular and it would be great for cucumber-kotlin to support code navigation when using customer parameter types.

**Comment by jlagerweij** [comment]
This now works in the 2020.2.x versions
