### ISSUE TITLE
Plugin doesn't work in Android Studio 3.6.1

### ISSUE THREAD

**Issue by cermakcz** [jlagerweij/cucumber-kotlin#18]
Android Studio 3.6.1 uses IntelliJ platform 2019.2 and the plugin version 1.1.1 doesn't work there (and 1.1.2 can't be installed).

I have a branch here https://github.com/cermakcz/cucumber-kotlin/tree/1.1.1-2019.2 which makes it work, but can't make a PR at this moment because a branch needs to be created first, since it branches from between 1.1.1 and 1.1.2 (which is not tagged, btw).

Also there's one more change here https://github.com/cermakcz/cucumber-kotlin/commit/65946b2ca8fc632fa904aef6a17688dde4a801d8#diff-9ceb2e549f3bd9b53584f751d31d64c9R71, which makes the plugin work properly in Android projects, when glue code is in a different module than the feature file. I tried the change also on a Kotlin project and it doesn't break anything (it's taken from the original Cucumber for Java plugin from JetBrains).

**Comment by jlagerweij** [comment]
For each version of product needs to be an update of this plugin as the Gherkin plugin has this limitation as well. The version is now limited to only what is known to work together.
