### ISSUE TITLE
IDEA 2020.1 compatibility

### ISSUE THREAD

**Issue by gtruitt** [jlagerweij/cucumber-kotlin#19]
IDEA 2020.1 provides the following error message when loading with this plugin installed:

`12:42 PM Plugin Error: Plugin "Cucumber for Kotlin" is incompatible (until build 193.SNAPSHOT < IU-201.6668.121).`

**Comment by jlagerweij** [comment]
The plugin has just been approved by JetBrains. The new version (1.1.3) is now available.
