### ISSUE TITLE
IDEA 2021.1 compatibility

### ISSUE THREAD

**Issue by tommari82** [jlagerweij/cucumber-kotlin#32]
Stat of IDEA 2021.1 show this error got this plugin
Plugin error: Plugin 'Cucumber for Kotlin' (version '2020.3.1') is not compatible with the current version of the IDE, because it requires build 203.* or older but the current build is IU-211.6693.111

**Comment by jlagerweij** [comment]
Minutes before you created this ticket I uploaded a new version of this plugin. 
If you cannot wait for the automatic Jetbrains push of the new version of the plugin, you can install it manualy:
https://plugins.jetbrains.com/plugin/10527-cucumber-for-kotlin/versions/stable/116216
