### ISSUE TITLE
Compatibility wirh 2021.3

### ISSUE THREAD

**Issue by alexvoss** [jlagerweij/cucumber-kotlin#38]
Hi, it looks like snap installs of IntelliJ have upgraded to 2021.3 recently. Any forecast when the plugin will be upgraded to be compatible with this? It gets flagged as incompatible. This should teach me to not use snap for IntelliJ at least... Thanks for the great work!

**Comment by jlagerweij** [comment]
Thank you for reaching out. I just pushed a release to Jetbrains Plugins. This will usually take a few days to be reviewed and is then publicly available.
