### ISSUE TITLE
Any one managed to see Cucumber reports for Espresso with Kotlin

### ISSUE THREAD

**Issue by rajchinta** [jlagerweij/cucumber-kotlin#4]
Hi, 

I'm using Expresso With Kotlin and my tests are running fine. Although I'm seeing "No tests were found" and "Empty Test suite" message under Android studio Espresso run console. I also had cucumber for Kotlin plugin as my one of the plugin for Android studio. 

Can anyone help me how to get cucumber reports for Espresso with Kotlin ?

Thanks

**Comment by jlagerweij** [comment]
This plugin lets you navigate from feature files to Kotlin step definitions and does nothing for Espresso. This question is better asked elsewhere.
