### ISSUE TITLE
Add support on IntelliJ IDEA 2022.2

### ISSUE THREAD

**Issue by DanielChesters** [jlagerweij/cucumber-kotlin#43]
Hi,

this week IntelliJ IDEA 2022.2 is out and Cucumber for Kotlin seems to be incompatible with this version:
![image](https://user-images.githubusercontent.com/291102/181588911-4f5da8b9-a458-493d-a0d7-7d83d27c386a.png)

Could you update this plugin for IntelliJ IDEA 2022.2? Thank you 🙏

**Comment by Zapevalov** [comment]
https://github.com/jlagerweij/cucumber-kotlin/pull/44

it remains only to wait :)

**Comment by Zapevalov** [comment]
You can build the plugin yourself from my branch and work fine with it

**Comment by jlagerweij** [comment]
I just published the plugin to Jetbrains. They will review it and after that it will be publicly available. Thank you for your contribution!
