### ISSUE TITLE
Not yet supporting by IntelliJ 2024.1

### ISSUE THREAD

**Issue by imfromthenet** [jlagerweij/cucumber-kotlin#63]
hello,

I updated the IntelliJ version to 2024.1 and noticed that the Cucumber plugin is not supported.

Thank you in advance :)

**Comment by j0bro** [comment]
+1 from me and the rest of my dev team!

**Comment by jlagerweij** [comment]
This was slightly more work than just changing version numbers, but the new version is sent to JetBrains for approval today. Should be available within 2 business days.

**Comment by imfromthenet** [comment]
got approved and released 👍 

thank you!
